modLoader="javafml"
license="MIT License https://github.com/McJtyMods/LostCities/blob/1.16/LICENCE"
loaderVersion="[47,)"
issueTrackerURL="http://github.com/McJtyMods/LostCities/issues"
displayURL="http://github.com/McJtyMods/LostCities/"
#logoFile="examplemod.png" #optional
#credits="Thanks for this example mod goes to Java" #optional
authors="McJty"

[[mods]]
modId="lostcities"
version="${file.jarVersion}"
displayName="LostCities"
#updateJSONURL="http://myurl.me/" #optional
description='''
Generate cities all over the world
'''
[[dependencies.lostcities]]
    modId="forge"
    mandatory=true
    versionRange="[43.1.30,)"
    ordering="NONE"
    side="BOTH"

# Optional soft dependency on Biomes O' Plenty
# Lost Cities will use BOP blocks/biomes when available, but works fine without it
[[dependencies.lostcities]]
    modId="biomesoplenty"
    mandatory=false
    versionRange="[18.0.0,)"
    ordering="AFTER"
    side="BOTH"

# Optional soft dependency on Lootr
# Lost Cities will use Lootr for per-player loot chests when available
[[dependencies.lostcities]]
    modId="lootr"
    mandatory=false
    versionRange="[1.10.0,)"
    ordering="AFTER"
    side="BOTH"
